


//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
namespace TypeWriter.Templates {
    
    /**
    * Interface for: HelloWorldDotNetify.Pages.Test.ITestState
    */
    export interface ITestState { 
        Test: string;
        Date: Date;
    }
}